/**
 * Counties Module — Seed Data
 *
 * Canonical default checklists for all permit types.
 * MobileHome checklist is based on the Lee County reference document.
 * All other permit types use standard Florida requirements.
 */

export type SeedRequirement = {
  documentName: string
  documentCategory: string
  permitTypes: string[]  // Use ['*'] for all types, or specific type codes
  isRequired: boolean
  isMandatoryForSubmission: boolean
  description?: string
  helpText?: string
  order: number
}

// ── All 67 Florida counties ──────────────────────────────────────────────────
export const FL_COUNTIES = [
  { name: 'Alachua',      code: 'ALA' }, { name: 'Baker',        code: 'BAK' },
  { name: 'Bay',          code: 'BAY' }, { name: 'Bradford',     code: 'BRA' },
  { name: 'Brevard',      code: 'BRE' }, { name: 'Broward',      code: 'BRO' },
  { name: 'Calhoun',      code: 'CAL' }, { name: 'Charlotte',    code: 'CHA' },
  { name: 'Citrus',       code: 'CIT' }, { name: 'Clay',         code: 'CLA' },
  { name: 'Collier',      code: 'COL' }, { name: 'Columbia',     code: 'CLM' },
  { name: 'DeSoto',       code: 'DES' }, { name: 'Dixie',        code: 'DIX' },
  { name: 'Duval',        code: 'DUV' }, { name: 'Escambia',     code: 'ESC' },
  { name: 'Flagler',      code: 'FLA' }, { name: 'Franklin',     code: 'FRK' },
  { name: 'Gadsden',      code: 'GAD' }, { name: 'Gilchrist',    code: 'GIL' },
  { name: 'Glades',       code: 'GLA' }, { name: 'Gulf',         code: 'GUL' },
  { name: 'Hamilton',     code: 'HAM' }, { name: 'Hardee',       code: 'HAR' },
  { name: 'Hendry',       code: 'HEN' }, { name: 'Hernando',     code: 'HER' },
  { name: 'Highlands',    code: 'HIG' }, { name: 'Hillsborough', code: 'HIL' },
  { name: 'Holmes',       code: 'HOL' }, { name: 'Indian River', code: 'IND' },
  { name: 'Jackson',      code: 'JAC' }, { name: 'Jefferson',    code: 'JEF' },
  { name: 'Lafayette',    code: 'LAF' }, { name: 'Lake',         code: 'LAK' },
  { name: 'Lee',          code: 'LEE' }, { name: 'Leon',         code: 'LEO' },
  { name: 'Levy',         code: 'LEV' }, { name: 'Liberty',      code: 'LIB' },
  { name: 'Madison',      code: 'MAD' }, { name: 'Manatee',      code: 'MAN' },
  { name: 'Marion',       code: 'MAR' }, { name: 'Martin',       code: 'MTN' },
  { name: 'Miami-Dade',   code: 'MIA' }, { name: 'Monroe',       code: 'MON' },
  { name: 'Nassau',       code: 'NAS' }, { name: 'Okaloosa',     code: 'OKA' },
  { name: 'Okeechobee',   code: 'OKE' }, { name: 'Orange',       code: 'ORA' },
  { name: 'Osceola',      code: 'OSC' }, { name: 'Palm Beach',   code: 'PAL' },
  { name: 'Pasco',        code: 'PAS' }, { name: 'Pinellas',     code: 'PIN' },
  { name: 'Polk',         code: 'POL' }, { name: 'Putnam',       code: 'PUT' },
  { name: 'Santa Rosa',   code: 'SAN' }, { name: 'Sarasota',     code: 'SAR' },
  { name: 'Seminole',     code: 'SEM' }, { name: 'St. Johns',    code: 'STJ' },
  { name: 'St. Lucie',    code: 'STL' }, { name: 'Sumter',       code: 'SUM' },
  { name: 'Suwannee',     code: 'SUW' }, { name: 'Taylor',       code: 'TAY' },
  { name: 'Union',        code: 'UNI' }, { name: 'Volusia',      code: 'VOL' },
  { name: 'Wakulla',      code: 'WAK' }, { name: 'Walton',       code: 'WAL' },
  { name: 'Washington',   code: 'WAS' },
] as const

export type FloridaCounty = (typeof FL_COUNTIES)[number]

// ── Default permit type definitions ─────────────────────────────────────────
export const DEFAULT_PERMIT_TYPES = [
  { code: 'Building',    label: 'Building',     order: 1, description: 'New construction, additions, and alterations' },
  { code: 'Electrical',  label: 'Electrical',   order: 2, description: 'Electrical service, wiring, and panel work' },
  { code: 'Plumbing',    label: 'Plumbing',     order: 3, description: 'Water supply, drain, waste, and vent systems' },
  { code: 'Mechanical',  label: 'Mechanical',   order: 4, description: 'Mechanical systems excluding HVAC' },
  { code: 'Roofing',     label: 'Roofing',      order: 5, description: 'Roof replacement, repair, and recover' },
  { code: 'HVAC',        label: 'HVAC',         order: 6, description: 'Heating, ventilation, and air conditioning' },
  { code: 'Structural',  label: 'Structural',   order: 7, description: 'Structural modifications and reinforcements' },
  { code: 'MobileHome',  label: 'Mobile Home',  order: 8, description: 'Mobile home installation and permits' },
  { code: 'Other',       label: 'Other',        order: 9, description: 'Miscellaneous permits not covered above' },
]

// ── Default requirements per permit type ────────────────────────────────────
// Source: MobileHome checklist from Lee County (May 2023)
// Other types: Standard Florida requirements
export const DEFAULT_REQUIREMENTS: SeedRequirement[] = [

  // ── Shared across ALL permit types ────────────────────────────────────────
  {
    documentName: 'Permit Application',
    documentCategory: 'Application',
    permitTypes: ['*'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Completed and signed permit application form',
    order: 1,
  },
  {
    documentName: 'Contractor License Copy',
    documentCategory: 'Application',
    permitTypes: ['*'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Current state contractor license',
    order: 2,
  },
  {
    documentName: "Workers' Compensation Certificate",
    documentCategory: 'Application',
    permitTypes: ['*'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: "Certificate of workers' compensation insurance",
    order: 3,
  },
  {
    documentName: 'Liability Insurance Certificate',
    documentCategory: 'Application',
    permitTypes: ['*'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'General liability insurance certificate',
    order: 4,
  },

  // ── Building ──────────────────────────────────────────────────────────────
  {
    documentName: 'Survey / Site Plan',
    documentCategory: 'Plans',
    permitTypes: ['Building'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Current survey and site plan showing property boundaries and setbacks',
    order: 10,
  },
  {
    documentName: 'Construction Plans',
    documentCategory: 'Plans',
    permitTypes: ['Building'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Full set of signed/sealed construction drawings',
    order: 11,
  },
  {
    documentName: 'Florida Energy Code Compliance',
    documentCategory: 'Engineering',
    permitTypes: ['Building'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Energy calculation report complying with Florida Building Code',
    order: 12,
  },
  {
    documentName: 'Structural Drawings',
    documentCategory: 'Engineering',
    permitTypes: ['Building'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Signed and sealed structural engineering drawings',
    order: 13,
  },
  {
    documentName: 'Notice of Commencement',
    documentCategory: 'Application',
    permitTypes: ['Building'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Recorded Notice of Commencement (projects over $2,500)',
    order: 14,
  },
  {
    documentName: 'Owner-Builder Disclosure',
    documentCategory: 'Application',
    permitTypes: ['Building'],
    isRequired: false,
    isMandatoryForSubmission: false,
    description: 'Required if owner is acting as their own contractor',
    helpText: 'Only required when owner-builder exemption is claimed',
    order: 15,
  },

  // ── Electrical ────────────────────────────────────────────────────────────
  {
    documentName: 'Electrical Plans / Diagram',
    documentCategory: 'Plans',
    permitTypes: ['Electrical'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Single-line diagram and panel schedule',
    order: 10,
  },
  {
    documentName: 'Load Calculation',
    documentCategory: 'Engineering',
    permitTypes: ['Electrical'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Electrical load calculation per NEC Article 220',
    order: 11,
  },
  {
    documentName: 'Equipment Specifications',
    documentCategory: 'Specifications',
    permitTypes: ['Electrical'],
    isRequired: false,
    isMandatoryForSubmission: false,
    description: 'Manufacturer specs for major electrical equipment',
    order: 12,
  },

  // ── Plumbing ──────────────────────────────────────────────────────────────
  {
    documentName: 'Plumbing Plans',
    documentCategory: 'Plans',
    permitTypes: ['Plumbing'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Supply, drain, waste, and vent layout drawings',
    order: 10,
  },
  {
    documentName: 'Isometric Drawing',
    documentCategory: 'Engineering',
    permitTypes: ['Plumbing'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Isometric diagram of drainage system',
    order: 11,
  },
  {
    documentName: 'Backflow Prevention Certificate',
    documentCategory: 'Certificate',
    permitTypes: ['Plumbing'],
    isRequired: false,
    isMandatoryForSubmission: false,
    description: 'Required for commercial projects or when backflow device is installed',
    order: 12,
  },

  // ── Mechanical ────────────────────────────────────────────────────────────
  {
    documentName: 'Mechanical Plans',
    documentCategory: 'Plans',
    permitTypes: ['Mechanical'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Mechanical system layout and specifications',
    order: 10,
  },
  {
    documentName: 'Equipment Specifications',
    documentCategory: 'Specifications',
    permitTypes: ['Mechanical'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Manufacturer cut sheets for mechanical equipment',
    order: 11,
  },

  // ── Roofing ───────────────────────────────────────────────────────────────
  {
    documentName: 'Roofing Plan / Diagram',
    documentCategory: 'Plans',
    permitTypes: ['Roofing'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Roof layout showing slope, materials, and deck type',
    order: 10,
  },
  {
    documentName: 'Florida Product Approval',
    documentCategory: 'Specifications',
    permitTypes: ['Roofing'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'FL product approval numbers for all roofing materials',
    helpText: 'Required per Florida Building Code Section 1507',
    order: 11,
  },
  {
    documentName: 'Notice of Commencement',
    documentCategory: 'Application',
    permitTypes: ['Roofing'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Recorded Notice of Commencement',
    order: 12,
  },

  // ── HVAC ──────────────────────────────────────────────────────────────────
  {
    documentName: 'HVAC Plans / Diagram',
    documentCategory: 'Plans',
    permitTypes: ['HVAC'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Duct layout, equipment location, and airflow diagram',
    order: 10,
  },
  {
    documentName: 'Manual J Load Calculation',
    documentCategory: 'Engineering',
    permitTypes: ['HVAC'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'ACCA Manual J residential load calculation report',
    order: 11,
  },
  {
    documentName: 'Equipment Specifications',
    documentCategory: 'Specifications',
    permitTypes: ['HVAC'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Manufacturer cut sheets for HVAC equipment',
    order: 12,
  },
  {
    documentName: 'Energy Efficiency Report',
    documentCategory: 'Engineering',
    permitTypes: ['HVAC'],
    isRequired: false,
    isMandatoryForSubmission: false,
    description: 'SEER rating documentation and Florida Energy Code compliance',
    order: 13,
  },

  // ── Structural ────────────────────────────────────────────────────────────
  {
    documentName: 'Survey / Site Plan',
    documentCategory: 'Plans',
    permitTypes: ['Structural'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Current survey showing existing and proposed conditions',
    order: 10,
  },
  {
    documentName: 'Structural Engineering Drawings',
    documentCategory: 'Engineering',
    permitTypes: ['Structural'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Signed and sealed structural drawings',
    order: 11,
  },
  {
    documentName: 'Structural Calculations',
    documentCategory: 'Engineering',
    permitTypes: ['Structural'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Signed and sealed structural engineering calculations',
    order: 12,
  },
  {
    documentName: 'Geotechnical / Soil Report',
    documentCategory: 'Engineering',
    permitTypes: ['Structural'],
    isRequired: false,
    isMandatoryForSubmission: false,
    description: 'Soil boring and geotechnical analysis (required for new foundations)',
    order: 13,
  },
  {
    documentName: 'Notice of Commencement',
    documentCategory: 'Application',
    permitTypes: ['Structural'],
    isRequired: true,
    isMandatoryForSubmission: true,
    order: 14,
  },

  // ── Mobile Home — from Lee County checklist (May 2023) ────────────────────
  {
    documentName: 'Survey / Site Plan',
    documentCategory: 'Plans',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Survey and site plan showing lot layout and setbacks',
    order: 10,
  },
  {
    documentName: 'Floor Plan',
    documentCategory: 'Plans',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Manufacturer floor plan for the mobile home unit',
    order: 11,
  },
  {
    documentName: 'Permit Worksheet',
    documentCategory: 'Application',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'County-specific permit worksheet (completed)',
    order: 12,
  },
  {
    documentName: 'Electrical Diagram',
    documentCategory: 'Engineering',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Electrical service and wiring diagram',
    order: 13,
  },
  {
    documentName: 'HVAC Diagram',
    documentCategory: 'Engineering',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'HVAC system diagram',
    order: 14,
  },
  {
    documentName: 'Notice of Commencement',
    documentCategory: 'Application',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Recorded Notice of Commencement',
    order: 15,
  },
  {
    documentName: 'Stair Detail',
    documentCategory: 'Plans',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Stair construction detail drawing',
    order: 16,
  },
  {
    documentName: 'Skirting Detail',
    documentCategory: 'Plans',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Skirting material and installation detail',
    order: 17,
  },
  {
    documentName: 'Tie-Down / Anchoring Detail',
    documentCategory: 'Engineering',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Anchor system and tie-down detail per HUD standards',
    helpText: 'Previously referred to as "Oliver Detail" in Lee County checklist',
    order: 18,
  },
  {
    documentName: 'Water / Sewer Letter',
    documentCategory: 'Correspondence',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Utility connection approval letter from water/sewer provider',
    order: 19,
  },
  {
    documentName: 'Manufacturer Manuals',
    documentCategory: 'Specifications',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: "Manufacturer's installation manual and data plate",
    helpText: 'Includes Jacobsen or equivalent manufacturer documentation',
    order: 20,
  },
  {
    documentName: 'Wind Zone Certification Letter',
    documentCategory: 'Correspondence',
    permitTypes: ['MobileHome'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Wind Zone 3 certification letter from manufacturer',
    helpText: 'Required for Florida Wind Zone 3 compliance',
    order: 21,
  },
  {
    documentName: 'Well Affidavit',
    documentCategory: 'Application',
    permitTypes: ['MobileHome'],
    isRequired: false,
    isMandatoryForSubmission: false,
    description: 'Well affidavit if property uses a private well',
    helpText: 'Required only if connecting to private well water supply',
    order: 22,
  },
  {
    documentName: 'Engineered Septic Design',
    documentCategory: 'Engineering',
    permitTypes: ['MobileHome'],
    isRequired: false,
    isMandatoryForSubmission: false,
    description: 'Engineer-designed septic system plan (required for septic permits)',
    helpText: 'All septics must be engineered. Contact Land Percs for Lee County.',
    order: 23,
  },
  {
    documentName: 'Impact Fee Letter',
    documentCategory: 'Correspondence',
    permitTypes: ['MobileHome'],
    isRequired: false,
    isMandatoryForSubmission: false,
    description: 'Impact fee assessment letter from county (if applicable)',
    helpText: 'Required only if impact fees apply to this installation',
    order: 24,
  },

  // ── Other ─────────────────────────────────────────────────────────────────
  {
    documentName: 'Project Description',
    documentCategory: 'Application',
    permitTypes: ['Other'],
    isRequired: true,
    isMandatoryForSubmission: true,
    description: 'Written description of the proposed work',
    order: 10,
  },
  {
    documentName: 'Supporting Plans / Documents',
    documentCategory: 'Plans',
    permitTypes: ['Other'],
    isRequired: false,
    isMandatoryForSubmission: false,
    description: 'Any plans, drawings, or documents relevant to the permit',
    order: 11,
  },
]
